#!/bin/sh
#
# collectord: Starts/stop the "collector" daemon
#
# chkconfig:   
# description: Starts/stops the python-based labstats collector daemon

### BEGIN INIT INFO
# Provides: 
# Required-Start: $local_fs
# Required-Stop: $local_fs
# Default-Start: 345
# Default-Stop: 95
# Short-Description: Starts/stops the python-based labstats collector daemon
# Description:  Starts/stops the python-based labstats collector daemon    
### END INIT INFO

# Goes in /etc/rc.d/init.d

# Source function library.
. /etc/rc.d/init.d/functions

dir=/afs/umich.edu/user/a/d/adrikim/labstatsMQ #temporary directory
prog="collector"

#config=/etc/sysconfig/atd
#[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog
#lockfile=/var/lock/subsys/$prog #not needed; scripts already check that?

start() {
    if [ $UID -ne 0 ] ; then
	echo "User has insufficient privilege."
	exit 4
    fi
    
    echo -n $"Starting $prog: " 
    # Store arguments here:
    # args=("$@")
    # TODO: how to use args to change pidfile directory (if needed)?
    python $dir/collector.py -d 
    retval=$?
}

stop() {
    if [ $UID -ne 0 ] ; then
	echo "User has insufficient privilege."
	exit 4
    fi
    
    MY_PID=`ps -ef | grep collector | grep python | awk '{print $2}'`
    echo -n "Stopping $prog: " $MY_PID
    kill $MY_PID
    RETVAL=3
    retval=$?
    echo
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    # run checks to determine if the service is running or use generic status
    status $prog
}

rh_status_q() {
    # 2>&1 means redirect stderr to stdout
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
	start
        #rh_status_q && exit 0
        ;;
    stop)
        stop
        #rh_status_q || exit 0
        ;;
    restart)
        restart
        ;;
    reload)
        #rh_status_q || exit 7
        reload
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
exit $?
